const INVENTORY_DATA = [
  {
    "id": "ARCNMRKD008",
    "computerName": "ARCNMRKD008",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.70",
    "activeUser": "frank",
    "userFullName": "Frank J. La Chira Gatica",
    "fullUser": "UTILESTWINS\\frank",
    "jobTitle": "Diseñador Gráfico",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "Gigabyte Technology Co., Ltd. B450M DS3H V2",
    "cpu": "AMD Ryzen 5 5600G with Radeon Graphics",
    "cpuShort": "AMD Ryzen 5 5600G with Radeon Graphics",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 2666MHz (Unknown)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "AMD Radeon(TM) Graphics",
    "gpuType": "integrated",
    "storage": "WDC WD10EZEX-00BBHA0 (932 GB) + WDC WDS480G2G0C-00AJM0 (447 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "LG UltraWide 29\" IPS (2560x1080 @ 59Hz)",
    "resolution": "2560x1080 @ 59Hz",
    "os": "Microsoft Windows 10",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG UltraWide 29\" IPS (2560x1080 @ 59Hz)",
        "brand": "LG",
        "model": "UltraWide 29\"",
        "serialNumber": "312NTNH6X335",
        "inventoryCode": "MN-MAR-001",
        "resolution": "2560x1080 @ 59Hz"
      },
      "keyboard": {
        "description": "LOGITECH K120 USB",
        "brand": "LOGITECH",
        "model": "K120 USB",
        "serialNumber": "2308SCS01Q78",
        "inventoryCode": "TCMAR001"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-008"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-001",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Antryx"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD010",
    "computerName": "ARCNMRKD010",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.72",
    "activeUser": "luz",
    "userFullName": "Luz",
    "fullUser": "UTILESTWINS\\luz",
    "jobTitle": "Diseñadora Gráfica Senior",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "ASUSTeK COMPUTER INC. TUF GAMING X570-PLUS (WI-FI)",
    "cpu": "AMD Ryzen 7 5700X 8-Core Processor",
    "cpuShort": "AMD Ryzen 7 5700X 8-Core Processor",
    "coresThreads": "8 Nucleos / 16 Hilos",
    "ramTotalGB": 32,
    "ramModules": "16 GB @ 2400MHz (Kingston) + 16 GB @ 2400MHz (Kingston)",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "NVIDIA GeForce RTX 4060 Ti",
    "gpuType": "dedicated",
    "storage": "KINGSTON SNV2S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "R9LMQS039161",
        "inventoryCode": "MN-MAR-003",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "2045SCK05EP8",
        "inventoryCode": "TCMAR003"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-010"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-003",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Antryx"
    },
    "alerts": [],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD011",
    "computerName": "ARCNMRKD011",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.73",
    "activeUser": "adrian",
    "userFullName": "Adrian",
    "fullUser": "UTILESTWINS\\adrian",
    "jobTitle": "Diseñador Audiovisual",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "Micro-Star International Co., Ltd. MAG B560 TOMAHAWK WIFI (MS-7D15)",
    "cpu": "11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz",
    "cpuShort": "11th Gen Intel(R) Core(TM) i5-11400F",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 32,
    "ramModules": "8 GB @ 3467MHz (A-DATA Technology) + 8 GB @ 3467MHz (A-DATA Technology) + 8 GB @ 3467MHz (A-DATA Technology) + 8 GB @ 3467MHz (A-DATA Technology)",
    "ramChannels": "Dual Channel (4 modulos)",
    "ramChannelType": "dual",
    "gpu": "NVIDIA GeForce RTX 3060 Ti",
    "gpuType": "dedicated",
    "storage": "WD Green SN350 1TB (932 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "N6LMQS125185",
        "inventoryCode": "MN-MAR-004",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "2308SCS01QA8",
        "inventoryCode": "TCMAR004"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-011"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-004",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "MS-7D15"
    },
    "alerts": [],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD012",
    "computerName": "ARCNMRKD012",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.74",
    "activeUser": "anjali",
    "userFullName": "Anjali N. Ramos Ramirez",
    "fullUser": "UTILESTWINS\\anjali",
    "jobTitle": "Diseñadora Gráfica",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "ASUSTeK COMPUTER INC. TUF GAMING X570-PLUS (WI-FI)",
    "cpu": "AMD Ryzen 7 5700X 8-Core Processor",
    "cpuShort": "AMD Ryzen 7 5700X 8-Core Processor",
    "coresThreads": "8 Nucleos / 16 Hilos",
    "ramTotalGB": 32,
    "ramModules": "16 GB @ 3600MHz (A-DATA) + 16 GB @ 3600MHz (A-DATA)",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "NVIDIA GeForce RTX 4060 Ti",
    "gpuType": "dedicated",
    "storage": "WDC WD10EZEX-00BBHA0 (932 GB) + WDC WD10EZEX-08WN4A0 (932 GB) + KINGSTON SNV2S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "N6LMQS168042",
        "inventoryCode": "MN-MAR-005",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "2227SCS05BD8",
        "inventoryCode": "TCMAR005"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-012"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-005",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Antryx"
    },
    "alerts": [],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD013",
    "computerName": "ARCNMRKD013",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.75",
    "activeUser": "zahir",
    "userFullName": "Zahir",
    "fullUser": "UTILESTWINS\\zahir",
    "jobTitle": "Diseñador Multimedia / 3D",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "ASUSTeK COMPUTER INC. TUF GAMING X570-PLUS (WI-FI)",
    "cpu": "AMD Ryzen 7 5700X 8-Core Processor",
    "cpuShort": "AMD Ryzen 7 5700X 8-Core Processor",
    "coresThreads": "8 Nucleos / 16 Hilos",
    "ramTotalGB": 32,
    "ramModules": "8 GB @ 3600MHz (A-DATA) + 8 GB @ 3600MHz (A-DATA) + 8 GB @ 3600MHz (A-DATA) + 8 GB @ 3600MHz (A-DATA)",
    "ramChannels": "Dual Channel (4 modulos)",
    "ramChannelType": "dual",
    "gpu": "NVIDIA GeForce RTX 3060",
    "gpuType": "dedicated",
    "storage": "WDC WD20EZBX-00AYRA0 (1863 GB) + KINGSTON SNV2S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "N6LMQS138650",
        "inventoryCode": "MN-MAR-006",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "HE013300806K2122",
        "inventoryCode": "TCMAR006"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-013"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-006",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD014",
    "computerName": "ARCNMRKD014",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.76",
    "activeUser": "sergio",
    "userFullName": "Sergio A. Vivas Azabache",
    "fullUser": "UTILESTWINS\\sergio",
    "jobTitle": "Diseñador Gráfico",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "ASUSTeK COMPUTER INC. TUF GAMING X570-PLUS (WI-FI)",
    "cpu": "AMD Ryzen 7 5700X 8-Core Processor",
    "cpuShort": "AMD Ryzen 7 5700X 8-Core Processor",
    "coresThreads": "N/D",
    "ramTotalGB": 64,
    "ramModules": "16 GB @ 2400MHz (Kingston) + 16 GB @ 2400MHz (A-DATA) + 16 GB @ 2400MHz (Kingston) + 16 GB @ 2400MHz (A-DATA)",
    "ramChannels": "Dual Channel (4 modulos)",
    "ramChannelType": "dual",
    "gpu": "NVIDIA GeForce RTX 4060 Ti",
    "gpuType": "dedicated",
    "storage": "1 TB SSD NVMe Ultrarrápido",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "N6LMQS125182",
        "inventoryCode": "MN-MAR-007",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "2308SCS01Q68",
        "inventoryCode": "TCMAR007"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-014"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-007",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Antryx"
    },
    "alerts": [],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD015",
    "computerName": "ARCNMRKD015",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.77",
    "activeUser": "adby",
    "userFullName": "Abdy N. Mamani Colque",
    "fullUser": "UTILESTWINS\\adby",
    "jobTitle": "Diseñadora Publicitaria",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "Gigabyte Technology Co., Ltd. B550 AORUS ELITE AX V2",
    "cpu": "AMD Ryzen 7 5700X 8-Core Processor",
    "cpuShort": "AMD Ryzen 7 5700X 8-Core Processor",
    "coresThreads": "8 Nucleos / 16 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 3600MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "NVIDIA GeForce GTX 1050 Ti",
    "gpuType": "dedicated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "LG FHD 24\" IPS 100Hz (1920x1080)",
    "resolution": "1920x1080 @ 100Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG FHD 24\" IPS 100Hz (1920x1080)",
        "brand": "LG",
        "model": "24MR400",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 100Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-DES-015"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-015"
      }
    },
    "assetCodes": {
      "pcCode": "PC-DESIGN-015",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Gigabyte Technology Co., Ltd. B550 AORUS ELITE AX V2"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD016",
    "computerName": "ARCNMRKD016",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.78",
    "activeUser": "danna",
    "userFullName": "Danna X. Cardenas",
    "fullUser": "UTILESTWINS\\danna",
    "jobTitle": "Asistente de Marketing",
    "department": "Marketing y Diseno",
    "category": "design",
    "formFactor": "Torre Creator RTX",
    "motherboard": "ASUSTeK COMPUTER INC. PRIME B760M-A D4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400F",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400F",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 3200MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "NVIDIA GeForce RTX 4060",
    "gpuType": "dedicated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
    "resolution": "2560x1440 @ 59Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS ProArt PA278CV 27\" 2K (2560x1440 @ 59Hz Calibrado sRGB)",
        "brand": "ASUS",
        "model": "ProArt PA278CV",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "2560x1440 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-DES-016"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-DES-016"
      }
    },
    "assetCodes": {
      "pcCode": "PC-DESIGN-016",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "ASUSTeK COMPUTER INC. PRIME B760M-A D4"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "creator_tower",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD001-1",
    "computerName": "ARCNADMD001-1",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.17",
    "activeUser": "roberto",
    "userFullName": "Roberto C. Rojas Farfán",
    "fullUser": "UTILESTWINS\\roberto",
    "jobTitle": "Asistente Contable",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 3200MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-0011"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-0011"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-0011",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD002",
    "computerName": "ARCNADMD002",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.221",
    "activeUser": "fiorela",
    "userFullName": "Fiorela L. Quispe Cruz",
    "fullUser": "UTILESTWINS\\fiorela",
    "jobTitle": "Analista Contable",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 3200MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350FZN",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350FZN",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "4PMFH4CW807255P",
        "inventoryCode": "MN-ADM-002",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "LOGITECH K120 USB",
        "brand": "LOGITECH",
        "model": "K120 USB",
        "serialNumber": "2306MR02DF58",
        "inventoryCode": "TCADM002"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-002"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADM-002",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD003",
    "computerName": "ARCNADMD003",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.22",
    "activeUser": "aranda",
    "userFullName": "Mayra I. Aranda Llauce",
    "fullUser": "UTILESTWINS\\aranda",
    "jobTitle": "Asistente Créditos & Cobranzas",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "ASUSTeK COMPUTER INC. PRIME B460M-A R2.0",
    "cpu": "Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz",
    "cpuShort": "Intel(R) Core(TM) i5-10400 CPU",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 8,
    "ramModules": "8 GB @ 2666MHz (CRUCIAL)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 630",
    "gpuType": "integrated",
    "storage": "KINGSTON SNVS500G (466 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350FZN",
    "resolution": "1920x1080 @ 59Hz",
    "os": "Microsoft Windows 10",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350FZN",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "4PMFH4CW808919B",
        "inventoryCode": "MN-ADM-003",
        "resolution": "1920x1080 @ 59Hz"
      },
      "keyboard": {
        "description": "LOGITECH K120 USB",
        "brand": "LOGITECH",
        "model": "K120 USB",
        "serialNumber": "2335MR293638",
        "inventoryCode": "TCADM003"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-003"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADM-003",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Asus"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 8GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD004-1",
    "computerName": "ARCNADMD004-1",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.222",
    "activeUser": "maribel",
    "userFullName": "Maribel M. Mendoza Cisneros",
    "fullUser": "UTILESTWINS\\maribel",
    "jobTitle": "Asistente Créditos & Cobranzas",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star PRO H610M-S DDR4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "N/D",
    "ramTotalGB": 16,
    "ramModules": "N/D",
    "ramChannels": "N/D",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics / AMD Radeon",
    "gpuType": "integrated",
    "storage": "1 TB SSD NVMe Ultrarrápido",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "N/D",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "N/D"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-0041"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-0041"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-0041",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star PRO H610M-S DDR4"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD005",
    "computerName": "ARCNADMD005",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.223",
    "activeUser": "kelly",
    "userFullName": "Kelly V. Símbala Carlos",
    "fullUser": "UTILESTWINS\\kelly",
    "jobTitle": "Asistente Créditos & Cobranzas",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. B450M-A PRO MAX II (MS-7C52)",
    "cpu": "AMD Ryzen 5 5600GT with Radeon Graphics",
    "cpuShort": "AMD Ryzen 5 5600GT with Radeon Graphics",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 2400MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "AMD Radeon(TM) Graphics",
    "gpuType": "integrated",
    "storage": "WD Blue SN580 2TB (1863 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "LG 24MS500",
    "resolution": "1920x1080 @ 100Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG 24MS500",
        "brand": "LG",
        "model": "24MS500",
        "serialNumber": "403NTMXD5131",
        "inventoryCode": "MN-ADM-005",
        "resolution": "1920x1080 @ 100Hz"
      },
      "keyboard": {
        "description": "LOGITECH K120 USB",
        "brand": "LOGITECH",
        "model": "K120 USB",
        "serialNumber": "2335MR2AF568",
        "inventoryCode": "TCADM005"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-005"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADM-005",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Micro-star"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD006",
    "computerName": "ARCNADMD006",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.224",
    "activeUser": "nelson",
    "userFullName": "Nelson A. Pasión Tarazona",
    "fullUser": "UTILESTWINS\\nelson",
    "jobTitle": "Auxiliar de Cobranzas",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. B450M-A PRO MAX II (MS-7C52)",
    "cpu": "AMD Ryzen 5 5600G with Radeon Graphics",
    "cpuShort": "AMD Ryzen 5 5600G with Radeon Graphics",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 2667MHz (Unknown)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "AMD Radeon(TM) Graphics",
    "gpuType": "integrated",
    "storage": "WDC WD10EZEX-00BBHA0 (932 GB) + WDC WDS480G2G0C-00AJM0 (447 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "Samsung S24R350FZN",
    "resolution": "1920x1080 @ 100Hz",
    "os": "Microsoft Windows 11",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350FZN",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "4PMFH4CW806146N",
        "inventoryCode": "MN-ADM-006",
        "resolution": "1920x1080 @ 100Hz"
      },
      "keyboard": {
        "description": "LOGITECH K120 USB",
        "brand": "LOGITECH",
        "model": "K120 USB",
        "serialNumber": "2337MR2DA9C8",
        "inventoryCode": "TCADM006"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-006"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADM-006",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADM007",
    "computerName": "ARCNADM007",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.220",
    "activeUser": "luis",
    "userFullName": "Luis A. Aramburu Bautista",
    "fullUser": "UTILESTWINS\\luis",
    "jobTitle": "Asistente Administrativo",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "ASUSTeK COMPUTER INC. H110M-E/M.2",
    "cpu": "Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz",
    "cpuShort": "Intel(R) Core(TM) i5-6400 CPU",
    "coresThreads": "4 Nucleos / 4 Hilos",
    "ramTotalGB": 12,
    "ramModules": "8 GB @ 2133MHz (CRUCIAL) + 4 GB @ 2133MHz (CRUCIAL)",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) HD Graphics 530",
    "gpuType": "integrated",
    "storage": "KINGSTON SA400S37480G (447 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 59Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-007"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-007"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-007",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "ASUSTeK COMPUTER INC. H110M-E/M.2"
    },
    "alerts": [],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD007",
    "computerName": "ARCNADMD007",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.43",
    "activeUser": "hugo",
    "userFullName": "Hugo Sebastian Martin Ingunza",
    "fullUser": "UTILESTWINS\\hugo",
    "jobTitle": "Administración General",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star PRO H610M-S DDR4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "N/D",
    "ramTotalGB": 16,
    "ramModules": "N/D",
    "ramChannels": "N/D",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics / AMD Radeon",
    "gpuType": "integrated",
    "storage": "1 TB SSD NVMe Ultrarrápido",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "N/D",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "N/D"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-007"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-007"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-007",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star PRO H610M-S DDR4"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD008",
    "computerName": "ARCNADMD008",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.225",
    "activeUser": "liz",
    "userFullName": "Liz M. Huaman Pongo",
    "fullUser": "UTILESTWINS\\liz",
    "jobTitle": "Asistente de Facturación",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 2400MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-008"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-008"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-008",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNADMD009",
    "computerName": "ARCNADMD009",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.227",
    "activeUser": "tania",
    "userFullName": "Tania Tarazona Tarazona",
    "fullUser": "UTILESTWINS\\tania",
    "jobTitle": "Tesorería & Finanzas",
    "department": "Administración y Finanzas",
    "category": "admin",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Gigabyte Technology Co., Ltd. B450M DS3H V2",
    "cpu": "AMD Ryzen 5 5600G with Radeon Graphics",
    "cpuShort": "AMD Ryzen 5 5600G with Radeon Graphics",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 3200MHz (Unknown)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "AMD Radeon(TM) Graphics",
    "gpuType": "integrated",
    "storage": "WDC WD10EZEX-00BBHA0 (932 GB) + WDC WDS480G2G0C-00AJM0 (447 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 100Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 100Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-ADM-009"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-ADM-009"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ADMIN-009",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Gigabyte Technology Co., Ltd. B450M DS3H V2"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNVNTD015",
    "computerName": "ARCNVNTD015",
    "status": "Desconectado",
    "isOnline": false,
    "ip": "192.168.18.12",
    "activeUser": "paula",
    "userFullName": "Paula P. Garcia Chavez",
    "fullUser": "UTILESTWINS\\paula",
    "jobTitle": "Vendedora de Campo",
    "department": "Ventas",
    "category": "sales",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star PRO H610M-S DDR4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "N/D",
    "ramTotalGB": 16,
    "ramModules": "N/D",
    "ramChannels": "N/D",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics / AMD Radeon",
    "gpuType": "integrated",
    "storage": "1 TB SSD NVMe Ultrarrápido",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "LG 24MS500",
    "resolution": "N/D",
    "os": "Microsoft Windows 11",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG 24MS500",
        "brand": "LG",
        "model": "24MS500",
        "serialNumber": "406NTVSB4983",
        "inventoryCode": "MN-VN-002",
        "resolution": "N/D"
      },
      "keyboard": {
        "description": "LOGITECH K120",
        "brand": "LOGITECH",
        "model": "K120",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SAL-015"
      }
    },
    "assetCodes": {
      "pcCode": "PC-VEN-002",
      "pcSerial": "------------------",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": null
  },
  {
    "id": "ARCNVNTD016",
    "computerName": "ARCNVNTD016",
    "status": "Desconectado",
    "isOnline": false,
    "ip": "192.168.18.42",
    "activeUser": "jhayro",
    "userFullName": "Shaulin Jhayro Mauricio Ciriaco",
    "fullUser": "UTILESTWINS\\jhayro",
    "jobTitle": "Vendedor de Campo",
    "department": "Ventas",
    "category": "sales",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star PRO H610M-S DDR4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "N/D",
    "ramTotalGB": 16,
    "ramModules": "N/D",
    "ramChannels": "N/D",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics / AMD Radeon",
    "gpuType": "integrated",
    "storage": "1 TB SSD NVMe Ultrarrápido",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung LS20D300NHPE",
    "resolution": "N/D",
    "os": "Microsoft Windows 11",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung LS20D300NHPE",
        "brand": "Samsung",
        "model": "LS20D300NHPE",
        "serialNumber": "ZZCWH4LJ10664P",
        "inventoryCode": "MN-VEN-001",
        "resolution": "N/D"
      },
      "keyboard": {
        "description": "Microsoft Wired 600 USB",
        "brand": "Microsoft",
        "model": "Wired 600 USB",
        "serialNumber": "0065818035610",
        "inventoryCode": "TCVEN001"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SAL-016"
      }
    },
    "assetCodes": {
      "pcCode": "PC-VEN-001",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": null
  },
  {
    "id": "ARCNVNTD019-1",
    "computerName": "ARCNVNTD019-1",
    "status": "Desconectado",
    "isOnline": false,
    "ip": "192.168.18.100",
    "activeUser": "jhenyfer",
    "userFullName": "Jhenyfer P. Barrantes Zelada",
    "fullUser": "UTILESTWINS\\jhenyfer",
    "jobTitle": "Coordinadora de Ventas",
    "department": "Ventas",
    "category": "sales",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 16,
    "ramModules": "16 GB @ 2400MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-SAL-0191"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SAL-0191"
      }
    },
    "assetCodes": {
      "pcCode": "PC-SALES-0191",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO H610M-S DDR4 (MS-7E44)"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 16GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": null
  },
  {
    "id": "ARCNALMD001",
    "computerName": "ARCNALMD001",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.79",
    "activeUser": "angelo",
    "userFullName": "Angelo J. Nuñez Durand",
    "fullUser": "UTILESTWINS\\angelo",
    "jobTitle": "Operario de Almacén",
    "department": "Almacén",
    "category": "warehouse",
    "formFactor": "Desktop Corporativo",
    "motherboard": "ASUSTeK COMPUTER INC. PRIME B360M-A",
    "cpu": "Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz",
    "cpuShort": "Intel(R) Core(TM) i3-8100 CPU",
    "coresThreads": "4 Nucleos / 4 Hilos",
    "ramTotalGB": 16,
    "ramModules": "8 GB @ 2400MHz (0B2C) + 8 GB @ 2400MHz (Kingston)",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) UHD Graphics 630",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "LG 22M38H-B 22\" FHD",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 10",
    "healthScore": 98,
    "location": {
      "floor": "Piso 1",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG 22M38H-B 22\" FHD",
        "brand": "LG",
        "model": "22M38H-B",
        "serialNumber": "701NTHMBQ713",
        "inventoryCode": "MN-ALM-007",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "SIN ASIGNAR",
        "inventoryCode": "TCALM001"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-WAR-001"
      }
    },
    "assetCodes": {
      "pcCode": "PC-ALM-002",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNTID002",
    "computerName": "ARCNTID002",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.88",
    "activeUser": "tajho",
    "userFullName": "Tajho A. Nuñez Durand",
    "fullUser": "UTILESTWINS\\tajho",
    "jobTitle": "Jefe de Sistemas TI",
    "department": "Sistemas TI",
    "category": "it",
    "formFactor": "Desktop Corporativo",
    "motherboard": "Gigabyte Technology Co., Ltd. B760M D3HP DDR4",
    "cpu": "12th Gen Intel(R) Core(TM) i5-12400",
    "cpuShort": "12th Gen Intel(R) Core(TM) i5-12400",
    "coresThreads": "6 Nucleos / 12 Hilos",
    "ramTotalGB": 32,
    "ramModules": "32 GB @ 2400MHz (Kingston)",
    "ramChannels": "Single Channel (1 modulo)",
    "ramChannelType": "single",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "LG FHD 27\" IPS 100Hz (601TFFP0F099)",
    "resolution": "1920x1080 @ 100Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 88,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "LG FHD 27\" IPS 100Hz (601TFFP0F099)",
        "brand": "LG",
        "model": "27MR400-B",
        "serialNumber": "601TFFP0F099",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 100Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-IT-002"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-IT-002"
      }
    },
    "assetCodes": {
      "pcCode": "PC-IT-002",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Gigabyte Technology Co., Ltd. B760M D3HP DDR4"
    },
    "alerts": [
      {
        "type": "warning",
        "title": "Single Channel RAM (64-bit)",
        "desc": "1 módulo de 32GB detectado. Añadir segundo módulo habilitará Dual Channel 128-bit (+18% ancho de banda)."
      }
    ],
    "deviceVisual": "admin_pc",
    "rttMs": 1
  },
  {
    "id": "ARCNMRKD009",
    "computerName": "ARCNMRKD009",
    "status": "Desconectado",
    "isOnline": false,
    "ip": "192.168.18.71",
    "activeUser": "sistemas",
    "userFullName": "Estación Soporte & Render TI",
    "fullUser": "UTILESTWINS\\sistemas",
    "jobTitle": "Estación TI (40GB / Almacenamiento)",
    "department": "Sistemas TI",
    "category": "it",
    "formFactor": "Desktop Corporativo",
    "motherboard": "ASUSTeK COMPUTER INC. PRIME Z270-A",
    "cpu": "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz",
    "cpuShort": "Intel(R) Core(TM) i7-7700 CPU",
    "coresThreads": "4 Nucleos / 8 Hilos",
    "ramTotalGB": 40,
    "ramModules": "8 GB @ 2400MHz (Kingston) + 16 GB @ 2400MHz (Kingston) + 16 GB @ 2400MHz (Corsair)",
    "ramChannels": "Dual Channel (3 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) HD Graphics 630",
    "gpuType": "integrated",
    "storage": "TOSHIBA HDWD110 (932 GB) + TOSHIBA EXTERNALUSB USB Device (1863 GB) + KINGSTON SA400S37240G (224 GB) + SanDisk SSD G5 BICS4 (466 GB)",
    "storageType": "SSD SATA / HDD",
    "monitor": "ASUS PA278CV",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 10",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Principal",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "ASUS PA278CV",
        "brand": "ASUS",
        "model": "PA278CV",
        "serialNumber": "N6LMQS138773",
        "inventoryCode": "MN-MAR-002",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "2343MR196848",
        "inventoryCode": "TCMAR002"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-IT-009"
      }
    },
    "assetCodes": {
      "pcCode": "PC-MAR-002",
      "pcSerial": "Sin número de serie",
      "pcBrand": "Compatible",
      "pcModel": "Compatible"
    },
    "alerts": [],
    "deviceVisual": "admin_pc",
    "rttMs": null
  },
  {
    "id": "SERVIDOR",
    "computerName": "SERVIDOR",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.200",
    "activeUser": "Administrador",
    "userFullName": "SERVIDOR (DC01)",
    "fullUser": "UTILESTWINS\\Administrador",
    "jobTitle": "Domain Controller & File Server",
    "department": "Servidores & Datacenter",
    "category": "servers",
    "formFactor": "Servidor Rackmount",
    "motherboard": "Micro-Star International Co., Ltd. PRO B760M-P (MS-7E02)",
    "cpu": "Intel(R) Core(TM) i7-14700",
    "cpuShort": "Intel(R) Core(TM) i7-14700",
    "coresThreads": "20 Nucleos / 28 Hilos",
    "ramTotalGB": 64,
    "ramModules": "32 GB @ 4800MHz (Kingston) + 32 GB @ 4800MHz (Kingston)",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) UHD Graphics 770",
    "gpuType": "integrated",
    "storage": "Samsung SSD 990 PRO 1TB (932 GB) + WD Green SN350 2TB (1863 GB) + WDC WD8002PURP-85C9JY0 (7452 GB)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1366x768 @ 59Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1366x768 @ 59Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-SER-"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SER-"
      }
    },
    "assetCodes": {
      "pcCode": "PC-SERVERS-",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO B760M-P (MS-7E02)"
    },
    "alerts": [],
    "deviceVisual": "server_rack",
    "rttMs": 1
  },
  {
    "id": "SERVERDB",
    "computerName": "SERVERDB",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.253",
    "activeUser": "SYSTEM",
    "userFullName": "SERVERDB (SQL Engine)",
    "fullUser": "UTILESTWINS\\SYSTEM",
    "jobTitle": "MS SQL Server SAP Business One",
    "department": "Servidores & Datacenter",
    "category": "servers",
    "formFactor": "Servidor Rackmount",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4",
    "cpu": "Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "6 Núcleos / 12 Hilos",
    "ramTotalGB": 32,
    "ramModules": "32 GB DDR4/DDR5 Enterprise",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB NVMe)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-SER-"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SER-"
      }
    },
    "assetCodes": {
      "pcCode": "PC-SERVERS-",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO H610M-S DDR4"
    },
    "alerts": [],
    "deviceVisual": "server_rack",
    "rttMs": 1
  },
  {
    "id": "SERVERAPP",
    "computerName": "SERVERAPP",
    "status": "En Linea",
    "isOnline": true,
    "ip": "192.168.18.254",
    "activeUser": "SYSTEM",
    "userFullName": "SERVERAPP (SAP Application)",
    "fullUser": "UTILESTWINS\\SYSTEM",
    "jobTitle": "SAP Business One Application Server",
    "department": "Servidores & Datacenter",
    "category": "servers",
    "formFactor": "Servidor Rackmount",
    "motherboard": "Micro-Star International Co., Ltd. PRO H610M-S DDR4",
    "cpu": "Intel(R) Core(TM) i5-12400 (6C/12T)",
    "cpuShort": "Intel(R) Core(TM) i5-12400 (6C/12T)",
    "coresThreads": "6 Núcleos / 12 Hilos",
    "ramTotalGB": 32,
    "ramModules": "32 GB DDR4/DDR5 Enterprise",
    "ramChannels": "Dual Channel (2 modulos)",
    "ramChannelType": "dual",
    "gpu": "Intel(R) UHD Graphics 730",
    "gpuType": "integrated",
    "storage": "KINGSTON SNV3S1000G (932 GB NVMe)",
    "storageType": "NVMe PCIe 4.0",
    "monitor": "Samsung S24R350 24\" IPS FHD (1920x1080)",
    "resolution": "1920x1080 @ 60Hz",
    "os": "Microsoft Windows 11 Pro 64-bit",
    "healthScore": 98,
    "location": {
      "floor": "Piso 4",
      "branch": "Sede Principal (San Martín de Porres / Lima)",
      "city": "Lima, Perú"
    },
    "peripherals": {
      "monitor": {
        "description": "Samsung S24R350 24\" IPS FHD (1920x1080)",
        "brand": "Samsung",
        "model": "S24R350FZN",
        "serialNumber": "N/D",
        "inventoryCode": "N/D",
        "resolution": "1920x1080 @ 60Hz"
      },
      "keyboard": {
        "description": "Logitech K120 USB",
        "brand": "Logitech",
        "model": "K120 USB",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "TC-SER-"
      },
      "mouse": {
        "description": "Logitech M90 Optical USB (1000 DPI)",
        "brand": "Logitech",
        "model": "M90 Optical USB (1000 DPI)",
        "serialNumber": "S/N Registrado en Ficha",
        "inventoryCode": "MS-SER-"
      }
    },
    "assetCodes": {
      "pcCode": "PC-SERVERS-",
      "pcSerial": "Sin número de serie (Custom Build)",
      "pcBrand": "Compatible / Custom Build",
      "pcModel": "Micro-Star International Co., Ltd. PRO H610M-S DDR4"
    },
    "alerts": [],
    "deviceVisual": "server_rack",
    "rttMs": 1
  }
];


const MOBILE_INVENTORY_DATA = [
  {
    "id": "MOB-ABDY-001",
    "activo": "ACT-MOV-2026-001",
    "colaborador": "Abdy Mamani",
    "cargo": "Gerente General / Directorio",
    "area": "Dirección",
    "dispositivo": "Apple iPhone 15 Pro Max",
    "modeloExacto": "MU773LL/A • A3106",
    "marca": "Apple",
    "colorEquipo": "Titanio Natural",
    "linea": "998 123 456",
    "operador": "Claro / Movistar PE",
    "imei1": "354892110482910",
    "imei2": "354892110482928 (eSIM Activa)",
    "serial": "F2LX90KL0M",
    "soc": "Apple A17 Pro (3nm Hexa-Core @ 3.78 GHz)",
    "gpu": "Apple 6-Core GPU Ray Tracing • 16-Core Neural Engine",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR5 Unified Memory",
    "romTotalGB": 256,
    "romTipo": "Apple NVMe High-Speed",
    "romUsado": "34.8 GB",
    "romLibre": "221.2 GB",
    "pantalla": "6.7\" Super Retina XDR OLED ProMotion 120Hz (2796x1290 px)",
    "bateria": "4,422 mAh Li-Ion Apple",
    "bateriaSalud": "100%",
    "bateriaCarga": "USB-C PD 27W • MagSafe 15W & Qi2",
    "camaras": "Triple Pro: 48 MP (OIS) + 12 MP Ultra Gran Angular + 12 MP 5x Telefoto Tetraprisma | Frontal 12 MP 4K60",
    "so": "iOS 18.2 • Build 22C150",
    "parche": "2026-02-01",
    "red": "5G NR Sub-6GHz / mmWave • Wi-Fi 6E • BT 5.3 • USB-C 3.2 (10Gbps)",
    "seguridad": "Face ID 3D Biometric • Titan M2 Security • IP68",
    "observaciones": "Terminal insignia de Dirección General. Estado estético y funcional 100% impecable. Vidrio templado 9H y case Spigen instalados.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_ABDY_MAMANI.pdf",
    "image": "images/phone_iphone15_promax_titanium.png",
    "isOnline": true
  },
  {
    "id": "MOB-FRANK-002",
    "activo": "ACT-MOV-2026-008",
    "colaborador": "Frank La Chira",
    "cargo": "Especialista en Marketing & Audiovisual",
    "area": "Marketing",
    "dispositivo": "Samsung Galaxy S23 Ultra 5G",
    "modeloExacto": "SM-S918B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Black",
    "linea": "941 012 876",
    "operador": "Claro PE",
    "imei1": "355465910643762",
    "imei2": "355465910643770",
    "serial": "R5CW13D0L5H",
    "soc": "Snapdragon 8 Gen 2 for Galaxy (4nm @ 3.36 GHz)",
    "gpu": "Qualcomm Adreno 740 Ray Tracing",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5X Ultra-Fast",
    "romTotalGB": 512,
    "romTipo": "UFS 4.0 High-Speed",
    "romUsado": "124.5 GB",
    "romLibre": "387.5 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X Edge 120Hz LTPO QHD+ (3088x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Super Rápida 45W • Inalámbrica 15W",
    "camaras": "Cuádruple Pro: 200 MP ISOCELL HP2 (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio 100x | Frontal 12 MP",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM • Wi-Fi 6E Tri-Band • BT 5.3 • S-Pen • DeX",
    "seguridad": "Sensor Huella Ultrasónico 3D en pantalla • Knox Vault • IP68",
    "observaciones": "Terminal primario de alta potencia asignado para captura audiovisual 4K/8K, edición publicitaria y gestión de redes sociales.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_FRANK_LA_CHIRA_SAMSUNG_S23_ULTRA.pdf",
    "image": "images/phone_samsung_s23_ultra.png",
    "isOnline": true
  },
  {
    "id": "MOB-LUIS-003",
    "activo": "ACT-MOV-2026-009",
    "colaborador": "Luis Aramburu",
    "cargo": "Administración & Finanzas",
    "area": "Administración & Finanzas",
    "dispositivo": "Huawei P30 Pro",
    "modeloExacto": "VOG-L04",
    "marca": "Huawei",
    "colorEquipo": "Breathing Crystal / Aurora",
    "linea": "981 234 567",
    "operador": "Claro PE",
    "imei1": "869175043303874",
    "imei2": "869175043303882",
    "serial": "45C0220121000381",
    "soc": "HiSilicon Kirin 980 (7nm Octa-Core @ 2.6 GHz + Dual NPU)",
    "gpu": "ARM Mali-G76 MP10 con GPU Turbo 3.0",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X Dual-Channel",
    "romTotalGB": 256,
    "romTipo": "UFS 2.1 Flash Storage",
    "romUsado": "68.2 GB",
    "romLibre": "187.8 GB",
    "pantalla": "6.47\" OLED Curvo FHD+ (2340x1080 px), HDR10",
    "bateria": "4,200 mAh Li-Po",
    "bateriaSalud": "97%",
    "bateriaCarga": "Huawei SuperCharge 40W • Inalámbrica 15W",
    "camaras": "Cuádruple Leica: 40 MP SuperSpectrum (f/1.6 OIS) + 20 MP Ultra Gran Angular + 8 MP Periscopio 50x (OIS) + ToF 3D | Frontal 32 MP",
    "so": "Android 12 • EMUI 12.0.0 (Google Services Nativos)",
    "parche": "2026-01-01",
    "red": "4G LTE Cat.21 (1.4Gbps) • Wi-Fi 5 Dual • BT 5.0 LE • NFC",
    "seguridad": "Huella óptica en pantalla • Reconocimiento Facial • IP68",
    "observaciones": "Terminal de alta gama asignado para gestión de cuentas, comunicaciones bancarias y soporte administrativo. Óptica Leica operativa con zoom 5x.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_LUIS_ARAMBURU.pdf",
    "image": "images/phone_huawei_p30_pro.png",
    "isOnline": true
  },
  {
    "id": "MOB-MARIBEL-004",
    "activo": "ACT-MOV-2026-003",
    "colaborador": "Maribel Mendoza",
    "cargo": "Jefa de Facturación & Cobranzas",
    "area": "Facturación & Cobranzas",
    "dispositivo": "Samsung Galaxy S22 Ultra 5G",
    "modeloExacto": "SM-S908E/DS",
    "marca": "Samsung",
    "colorEquipo": "Burgundy / Phantom Black",
    "linea": "976 543 210",
    "operador": "Claro PE",
    "imei1": "352984110394857",
    "imei2": "352984110394865",
    "serial": "R5CT309876A",
    "soc": "Qualcomm Snapdragon 8 Gen 1 (4nm @ 3.0 GHz)",
    "gpu": "Qualcomm Adreno 730",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "51.4 GB",
    "romLibre": "204.6 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X Edge 120Hz LTPO QHD+ (3088x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Ultra Rápida 45W • Inalámbrica 15W",
    "camaras": "Cuádruple Pro: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Space Zoom 100x | Frontal 40 MP Pro",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • S-Pen • DeX",
    "seguridad": "Huella Ultrasónica 3D • Knox Security 3.9 • IP68",
    "observaciones": "Terminal de alta gama asignado para gestión de cuentas por cobrar, emisión de comprobantes y firma digital con S-Pen.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_MARIBEL_MENDOZA.pdf",
    "image": "images/phone_samsung_s22_ultra.png",
    "isOnline": true
  },
  {
    "id": "MOB-KELLY-005",
    "activo": "ACT-MOV-2026-004",
    "colaborador": "Kelly Simbala",
    "cargo": "Ejecutiva Senior de Ventas",
    "area": "Ventas & Comercial",
    "dispositivo": "Samsung Galaxy S21 Ultra 5G",
    "modeloExacto": "SM-G998B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Silver",
    "linea": "986 561 578",
    "operador": "Movistar PE",
    "imei1": "358941110293847",
    "imei2": "358941110293854",
    "serial": "R5CR10ABCDE",
    "soc": "Samsung Exynos 2100 (5nm EUV Octa-Core @ 2.9 GHz)",
    "gpu": "ARM Mali-G78 MP14",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "45.8 GB",
    "romLibre": "210.2 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X WQHD+ 120Hz (3200x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Rápida 25W USB-C PD • Inalámbrica 15W",
    "camaras": "Cuádruple: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio | Frontal 40 MP 4K",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • NFC • DeX",
    "seguridad": "Sensor Ultrasónico 3D en pantalla • Knox Security 3.9 • IP68",
    "observaciones": "Terminal comercial insignia asignado para contacto prioritario con mayoristas, atención de cotizaciones y pedidos.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_KELLY_SIMBALA.pdf",
    "image": "images/phone_samsung_s21_ultra_silver.png",
    "isOnline": true
  },
  {
    "id": "MOB-LIZ-006",
    "activo": "ACT-MOV-2026-002",
    "colaborador": "Liz Huaman",
    "cargo": "Administradora General & Control Financiero",
    "area": "Administración & Finanzas",
    "dispositivo": "Samsung Galaxy S21 Ultra 5G",
    "modeloExacto": "SM-G998B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Black",
    "linea": "987 456 123",
    "operador": "Entel PE",
    "imei1": "358941110829103",
    "imei2": "358941110829111",
    "serial": "R5CR20FEDCB",
    "soc": "Samsung Exynos 2100 (5nm EUV Octa-Core @ 2.9 GHz)",
    "gpu": "ARM Mali-G78 MP14",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "42.1 GB",
    "romLibre": "213.9 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X WQHD+ 120Hz (3200x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Rápida 25W USB-C PD • Inalámbrica 15W",
    "camaras": "Cuádruple: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio | Frontal 40 MP 4K",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • NFC • DeX",
    "seguridad": "Sensor Ultrasónico 3D en pantalla • Knox Security 3.9 • IP68",
    "observaciones": "Terminal asignado para control de flujos de caja, banca electrónica empresarial y autorizaciones de pago con token digital.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_LIZ_HUAMAN.pdf",
    "image": "images/phone_samsung_s21_ultra_black.png",
    "isOnline": true
  },
  {
    "id": "MOB-HUGO-007",
    "activo": "ACT-MOV-2026-010",
    "colaborador": "Hugo Ingunza",
    "cargo": "Jefe de Recursos Humanos & Talento",
    "area": "RR.HH",
    "dispositivo": "Samsung Galaxy SM-A376B",
    "modeloExacto": "SM-A376B/DS (Galaxy A35/A37 5G)",
    "marca": "Samsung",
    "colorEquipo": "Awesome Navy / Ice Blue",
    "linea": "944 588 955",
    "operador": "Claro PE",
    "imei1": "358372340639278",
    "imei2": "No Aplica (Single SIM / eSIM standby)",
    "serial": "RFGL42EV9YB",
    "soc": "Samsung Exynos Octa-Core @ 2.2 GHz (S5E8845)",
    "gpu": "ARM Mali / Qualcomm Adreno",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X",
    "romTotalGB": 256,
    "romTipo": "UFS 2.2 Flash Storage",
    "romUsado": "29.2 GB",
    "romLibre": "194.6 GB",
    "pantalla": "6.67\" Super AMOLED FHD+ 120Hz (2340x1080 px)",
    "bateria": "5,000 mAh Li-Po",
    "bateriaSalud": "13% • Excelente (Good)",
    "bateriaCarga": "Carga Rápida 25W USB Type-C • 30.2 °C",
    "camaras": "Triple: 108 MP Principal + 8 MP Gran Angular + 2 MP Macro | Frontal 16 MP",
    "so": "Android 16 • Samsung One UI v8.5",
    "parche": "2026-07-05",
    "red": "5G / 4G LTE-A • Wi-Fi 802.11 a/b/g/n/ac • BT 5.2 • NFC",
    "seguridad": "Lector de huellas dactilares bajo pantalla • Knox Vault",
    "observaciones": "Recomendación técnica emitida: Colocar mica protectora de pantalla 9D y case de alto impacto antichoques.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_HUGO_INGUNZA.pdf",
    "image": "images/phone_samsung_a35_5g.png",
    "isOnline": true
  },
  {
    "id": "MOB-MAYRA-008",
    "activo": "ACT-MOV-2026-005",
    "colaborador": "Mayra Aranda",
    "cargo": "Contadora General & Tesorería",
    "area": "Contabilidad & Tesorería",
    "dispositivo": "Xiaomi Mi 10T Pro 5G",
    "modeloExacto": "M2007J3SG",
    "marca": "Xiaomi",
    "colorEquipo": "Lunar Silver",
    "linea": "965 432 109",
    "operador": "Movistar PE",
    "imei1": "864920048291038",
    "imei2": "864920048291046",
    "serial": "28934/A0192837",
    "soc": "Qualcomm Snapdragon 865 5G (7nm+ @ 2.84 GHz)",
    "gpu": "Qualcomm Adreno 650",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "58.3 GB",
    "romLibre": "197.7 GB",
    "pantalla": "6.67\" IPS LCD DotDisplay FHD+ 144Hz AdaptiveSync (2400x1080 px)",
    "bateria": "5,000 mAh Li-Po MMT",
    "bateriaSalud": "98%",
    "bateriaCarga": "Mi Fast Charge 33W USB Type-C",
    "camaras": "Triple: 108 MP Principal Samsung HMX (OIS) + 13 MP Ultra Gran Angular 123° + 5 MP Macro | Frontal 20 MP",
    "so": "Android 14 • Xiaomi HyperOS v1.0.8",
    "parche": "2026-01-01",
    "red": "5G Standby Dual SIM • Wi-Fi 6 (802.11ax) • BT 5.1 • NFC • IR",
    "seguridad": "Sensor de huellas lateral ergonómico • Desbloqueo Facial AI",
    "observaciones": "Terminal contable de alto rendimiento para validación de comprobantes, portales SUNAT y conciliaciones bancarias móviles.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_MAYRA_ARANDA.pdf",
    "image": "images/phone_xiaomi_mi10t_pro.png",
    "isOnline": true
  },
  {
    "id": "MOB-TANIA-009",
    "activo": "ACT-MOV-2026-006",
    "colaborador": "Tania Tarazona",
    "cargo": "Coordinadora de Despacho & Logística",
    "area": "Logística & Despacho",
    "dispositivo": "Xiaomi Redmi Note 15",
    "modeloExacto": "24116RN98G",
    "marca": "Xiaomi",
    "colorEquipo": "Ice Blue",
    "linea": "954 321 098",
    "operador": "Claro PE",
    "imei1": "869102068291039",
    "imei2": "869102068291047",
    "serial": "30192/B9281726",
    "soc": "MediaTek Helio G99-Ultra / G100 (6nm @ 2.2 GHz)",
    "gpu": "ARM Mali-G57 MC2 Dual-Core @ 950 MHz",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X",
    "romTotalGB": 256,
    "romTipo": "UFS 2.2 Flash Storage",
    "romUsado": "38.9 GB",
    "romLibre": "217.1 GB",
    "pantalla": "6.67\" AMOLED FHD+ 120Hz (2400x1080 px), 1800 nits",
    "bateria": "5,000 mAh Li-Po",
    "bateriaSalud": "100%",
    "bateriaCarga": "Turbo Charge 33W USB Type-C",
    "camaras": "Triple: 108 MP Principal (1/1.67\") + 8 MP Ultra Gran Angular 118° + 2 MP Macro | Frontal 16 MP",
    "so": "Android 15 • Xiaomi HyperOS v2.0.2",
    "parche": "2026-02-01",
    "red": "Dual SIM 4G VoLTE • Wi-Fi 5 Dual-Band • BT 5.2 • NFC • IR Blaster",
    "seguridad": "Sensor de huellas óptico bajo pantalla • Certificación IP54",
    "observaciones": "Terminal de operaciones de campo para coordinación de transportistas, seguimiento satelital y recepción de mercadería.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_TANIA_TARAZONA.pdf",
    "image": "images/phone_xiaomi_redmi_note13_blue.png",
    "isOnline": true
  }
];

if (typeof window !== "undefined") {
  window.INVENTORY_DATA = INVENTORY_DATA;
  window.MOBILE_INVENTORY_DATA = MOBILE_INVENTORY_DATA;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { INVENTORY_DATA, MOBILE_INVENTORY_DATA };
}

const MOBILE_FLEET = [
  {
    "id": "MOB-ABDY-001",
    "activo": "ACT-MOV-2026-001",
    "colaborador": "Abdy Mamani",
    "cargo": "Gerente General / Directorio",
    "area": "Dirección",
    "dispositivo": "Apple iPhone 15 Pro Max",
    "modeloExacto": "MU773LL/A • A3106",
    "marca": "Apple",
    "colorEquipo": "Titanio Natural",
    "linea": "998 123 456",
    "operador": "Claro / Movistar PE",
    "imei1": "354892110482910",
    "imei2": "354892110482928 (eSIM Activa)",
    "serial": "F2LX90KL0M",
    "soc": "Apple A17 Pro (3nm Hexa-Core @ 3.78 GHz)",
    "gpu": "Apple 6-Core GPU Ray Tracing • 16-Core Neural Engine",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR5 Unified Memory",
    "romTotalGB": 256,
    "romTipo": "Apple NVMe High-Speed",
    "romUsado": "34.8 GB",
    "romLibre": "221.2 GB",
    "pantalla": "6.7\" Super Retina XDR OLED ProMotion 120Hz (2796x1290 px)",
    "bateria": "4,422 mAh Li-Ion Apple",
    "bateriaSalud": "100%",
    "bateriaCarga": "USB-C PD 27W • MagSafe 15W & Qi2",
    "camaras": "Triple Pro: 48 MP (OIS) + 12 MP Ultra Gran Angular + 12 MP 5x Telefoto Tetraprisma | Frontal 12 MP 4K60",
    "so": "iOS 18.2 • Build 22C150",
    "parche": "2026-02-01",
    "red": "5G NR Sub-6GHz / mmWave • Wi-Fi 6E • BT 5.3 • USB-C 3.2 (10Gbps)",
    "seguridad": "Face ID 3D Biometric • Titan M2 Security • IP68",
    "observaciones": "Terminal insignia de Dirección General. Estado estético y funcional 100% impecable. Vidrio templado 9H y case Spigen instalados.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_ABDY_MAMANI.pdf",
    "image": "images/phone_iphone15_promax_titanium.png",
    "isOnline": true
  },
  {
    "id": "MOB-FRANK-002",
    "activo": "ACT-MOV-2026-008",
    "colaborador": "Frank La Chira",
    "cargo": "Especialista en Marketing & Audiovisual",
    "area": "Marketing",
    "dispositivo": "Samsung Galaxy S23 Ultra 5G",
    "modeloExacto": "SM-S918B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Black",
    "linea": "941 012 876",
    "operador": "Claro PE",
    "imei1": "355465910643762",
    "imei2": "355465910643770",
    "serial": "R5CW13D0L5H",
    "soc": "Snapdragon 8 Gen 2 for Galaxy (4nm @ 3.36 GHz)",
    "gpu": "Qualcomm Adreno 740 Ray Tracing",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5X Ultra-Fast",
    "romTotalGB": 512,
    "romTipo": "UFS 4.0 High-Speed",
    "romUsado": "124.5 GB",
    "romLibre": "387.5 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X Edge 120Hz LTPO QHD+ (3088x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Super Rápida 45W • Inalámbrica 15W",
    "camaras": "Cuádruple Pro: 200 MP ISOCELL HP2 (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio 100x | Frontal 12 MP",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM • Wi-Fi 6E Tri-Band • BT 5.3 • S-Pen • DeX",
    "seguridad": "Sensor Huella Ultrasónico 3D en pantalla • Knox Vault • IP68",
    "observaciones": "Terminal primario de alta potencia asignado para captura audiovisual 4K/8K, edición publicitaria y gestión de redes sociales.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_FRANK_LA_CHIRA_SAMSUNG_S23_ULTRA.pdf",
    "image": "images/phone_samsung_s23_ultra.png",
    "isOnline": true
  },
  {
    "id": "MOB-LUIS-003",
    "activo": "ACT-MOV-2026-009",
    "colaborador": "Luis Aramburu",
    "cargo": "Administración & Finanzas",
    "area": "Administración & Finanzas",
    "dispositivo": "Huawei P30 Pro",
    "modeloExacto": "VOG-L04",
    "marca": "Huawei",
    "colorEquipo": "Breathing Crystal / Aurora",
    "linea": "981 234 567",
    "operador": "Claro PE",
    "imei1": "869175043303874",
    "imei2": "869175043303882",
    "serial": "45C0220121000381",
    "soc": "HiSilicon Kirin 980 (7nm Octa-Core @ 2.6 GHz + Dual NPU)",
    "gpu": "ARM Mali-G76 MP10 con GPU Turbo 3.0",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X Dual-Channel",
    "romTotalGB": 256,
    "romTipo": "UFS 2.1 Flash Storage",
    "romUsado": "68.2 GB",
    "romLibre": "187.8 GB",
    "pantalla": "6.47\" OLED Curvo FHD+ (2340x1080 px), HDR10",
    "bateria": "4,200 mAh Li-Po",
    "bateriaSalud": "97%",
    "bateriaCarga": "Huawei SuperCharge 40W • Inalámbrica 15W",
    "camaras": "Cuádruple Leica: 40 MP SuperSpectrum (f/1.6 OIS) + 20 MP Ultra Gran Angular + 8 MP Periscopio 50x (OIS) + ToF 3D | Frontal 32 MP",
    "so": "Android 12 • EMUI 12.0.0 (Google Services Nativos)",
    "parche": "2026-01-01",
    "red": "4G LTE Cat.21 (1.4Gbps) • Wi-Fi 5 Dual • BT 5.0 LE • NFC",
    "seguridad": "Huella óptica en pantalla • Reconocimiento Facial • IP68",
    "observaciones": "Terminal de alta gama asignado para gestión de cuentas, comunicaciones bancarias y soporte administrativo. Óptica Leica operativa con zoom 5x.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_LUIS_ARAMBURU.pdf",
    "image": "images/phone_huawei_p30_pro.png",
    "isOnline": true
  },
  {
    "id": "MOB-MARIBEL-004",
    "activo": "ACT-MOV-2026-003",
    "colaborador": "Maribel Mendoza",
    "cargo": "Jefa de Facturación & Cobranzas",
    "area": "Facturación & Cobranzas",
    "dispositivo": "Samsung Galaxy S22 Ultra 5G",
    "modeloExacto": "SM-S908E/DS",
    "marca": "Samsung",
    "colorEquipo": "Burgundy / Phantom Black",
    "linea": "976 543 210",
    "operador": "Claro PE",
    "imei1": "352984110394857",
    "imei2": "352984110394865",
    "serial": "R5CT309876A",
    "soc": "Qualcomm Snapdragon 8 Gen 1 (4nm @ 3.0 GHz)",
    "gpu": "Qualcomm Adreno 730",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "51.4 GB",
    "romLibre": "204.6 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X Edge 120Hz LTPO QHD+ (3088x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Ultra Rápida 45W • Inalámbrica 15W",
    "camaras": "Cuádruple Pro: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Space Zoom 100x | Frontal 40 MP Pro",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • S-Pen • DeX",
    "seguridad": "Huella Ultrasónica 3D • Knox Security 3.9 • IP68",
    "observaciones": "Terminal de alta gama asignado para gestión de cuentas por cobrar, emisión de comprobantes y firma digital con S-Pen.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_MARIBEL_MENDOZA.pdf",
    "image": "images/phone_samsung_s22_ultra.png",
    "isOnline": true
  },
  {
    "id": "MOB-KELLY-005",
    "activo": "ACT-MOV-2026-004",
    "colaborador": "Kelly Simbala",
    "cargo": "Ejecutiva Senior de Ventas",
    "area": "Ventas & Comercial",
    "dispositivo": "Samsung Galaxy S21 Ultra 5G",
    "modeloExacto": "SM-G998B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Silver",
    "linea": "986 561 578",
    "operador": "Movistar PE",
    "imei1": "358941110293847",
    "imei2": "358941110293854",
    "serial": "R5CR10ABCDE",
    "soc": "Samsung Exynos 2100 (5nm EUV Octa-Core @ 2.9 GHz)",
    "gpu": "ARM Mali-G78 MP14",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "45.8 GB",
    "romLibre": "210.2 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X WQHD+ 120Hz (3200x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Rápida 25W USB-C PD • Inalámbrica 15W",
    "camaras": "Cuádruple: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio | Frontal 40 MP 4K",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • NFC • DeX",
    "seguridad": "Sensor Ultrasónico 3D en pantalla • Knox Security 3.9 • IP68",
    "observaciones": "Terminal comercial insignia asignado para contacto prioritario con mayoristas, atención de cotizaciones y pedidos.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_KELLY_SIMBALA.pdf",
    "image": "images/phone_samsung_s21_ultra_silver.png",
    "isOnline": true
  },
  {
    "id": "MOB-LIZ-006",
    "activo": "ACT-MOV-2026-002",
    "colaborador": "Liz Huaman",
    "cargo": "Administradora General & Control Financiero",
    "area": "Administración & Finanzas",
    "dispositivo": "Samsung Galaxy S21 Ultra 5G",
    "modeloExacto": "SM-G998B/DS",
    "marca": "Samsung",
    "colorEquipo": "Phantom Black",
    "linea": "987 456 123",
    "operador": "Entel PE",
    "imei1": "358941110829103",
    "imei2": "358941110829111",
    "serial": "R5CR20FEDCB",
    "soc": "Samsung Exynos 2100 (5nm EUV Octa-Core @ 2.9 GHz)",
    "gpu": "ARM Mali-G78 MP14",
    "ramTotalGB": 12,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "42.1 GB",
    "romLibre": "213.9 GB",
    "pantalla": "6.8\" Dynamic AMOLED 2X WQHD+ 120Hz (3200x1440 px)",
    "bateria": "5,000 mAh Li-Ion",
    "bateriaSalud": "100%",
    "bateriaCarga": "Carga Rápida 25W USB-C PD • Inalámbrica 15W",
    "camaras": "Cuádruple: 108 MP (OIS) + 12 MP Ultra Gran Angular + 10 MP 3x + 10 MP 10x Periscopio | Frontal 40 MP 4K",
    "so": "Android 15 • Samsung One UI 7.0",
    "parche": "2026-02-01",
    "red": "5G Dual SIM + eSIM • Wi-Fi 6E • BT 5.2 • NFC • DeX",
    "seguridad": "Sensor Ultrasónico 3D en pantalla • Knox Security 3.9 • IP68",
    "observaciones": "Terminal asignado para control de flujos de caja, banca electrónica empresarial y autorizaciones de pago con token digital.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_LIZ_HUAMAN.pdf",
    "image": "images/phone_samsung_s21_ultra_black.png",
    "isOnline": true
  },
  {
    "id": "MOB-HUGO-007",
    "activo": "ACT-MOV-2026-010",
    "colaborador": "Hugo Ingunza",
    "cargo": "Jefe de Recursos Humanos & Talento",
    "area": "RR.HH",
    "dispositivo": "Samsung Galaxy SM-A376B",
    "modeloExacto": "SM-A376B/DS (Galaxy A35/A37 5G)",
    "marca": "Samsung",
    "colorEquipo": "Awesome Navy / Ice Blue",
    "linea": "944 588 955",
    "operador": "Claro PE",
    "imei1": "358372340639278",
    "imei2": "No Aplica (Single SIM / eSIM standby)",
    "serial": "RFGL42EV9YB",
    "soc": "Samsung Exynos Octa-Core @ 2.2 GHz (S5E8845)",
    "gpu": "ARM Mali / Qualcomm Adreno",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X",
    "romTotalGB": 256,
    "romTipo": "UFS 2.2 Flash Storage",
    "romUsado": "29.2 GB",
    "romLibre": "194.6 GB",
    "pantalla": "6.67\" Super AMOLED FHD+ 120Hz (2340x1080 px)",
    "bateria": "5,000 mAh Li-Po",
    "bateriaSalud": "13% • Excelente (Good)",
    "bateriaCarga": "Carga Rápida 25W USB Type-C • 30.2 °C",
    "camaras": "Triple: 108 MP Principal + 8 MP Gran Angular + 2 MP Macro | Frontal 16 MP",
    "so": "Android 16 • Samsung One UI v8.5",
    "parche": "2026-07-05",
    "red": "5G / 4G LTE-A • Wi-Fi 802.11 a/b/g/n/ac • BT 5.2 • NFC",
    "seguridad": "Lector de huellas dactilares bajo pantalla • Knox Vault",
    "observaciones": "Recomendación técnica emitida: Colocar mica protectora de pantalla 9D y case de alto impacto antichoques.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_HUGO_INGUNZA.pdf",
    "image": "images/phone_samsung_a35_5g.png",
    "isOnline": true
  },
  {
    "id": "MOB-MAYRA-008",
    "activo": "ACT-MOV-2026-005",
    "colaborador": "Mayra Aranda",
    "cargo": "Contadora General & Tesorería",
    "area": "Contabilidad & Tesorería",
    "dispositivo": "Xiaomi Mi 10T Pro 5G",
    "modeloExacto": "M2007J3SG",
    "marca": "Xiaomi",
    "colorEquipo": "Lunar Silver",
    "linea": "965 432 109",
    "operador": "Movistar PE",
    "imei1": "864920048291038",
    "imei2": "864920048291046",
    "serial": "28934/A0192837",
    "soc": "Qualcomm Snapdragon 865 5G (7nm+ @ 2.84 GHz)",
    "gpu": "Qualcomm Adreno 650",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR5 High-Speed",
    "romTotalGB": 256,
    "romTipo": "UFS 3.1 Flash Storage",
    "romUsado": "58.3 GB",
    "romLibre": "197.7 GB",
    "pantalla": "6.67\" IPS LCD DotDisplay FHD+ 144Hz AdaptiveSync (2400x1080 px)",
    "bateria": "5,000 mAh Li-Po MMT",
    "bateriaSalud": "98%",
    "bateriaCarga": "Mi Fast Charge 33W USB Type-C",
    "camaras": "Triple: 108 MP Principal Samsung HMX (OIS) + 13 MP Ultra Gran Angular 123° + 5 MP Macro | Frontal 20 MP",
    "so": "Android 14 • Xiaomi HyperOS v1.0.8",
    "parche": "2026-01-01",
    "red": "5G Standby Dual SIM • Wi-Fi 6 (802.11ax) • BT 5.1 • NFC • IR",
    "seguridad": "Sensor de huellas lateral ergonómico • Desbloqueo Facial AI",
    "observaciones": "Terminal contable de alto rendimiento para validación de comprobantes, portales SUNAT y conciliaciones bancarias móviles.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_MAYRA_ARANDA.pdf",
    "image": "images/phone_xiaomi_mi10t_pro.png",
    "isOnline": true
  },
  {
    "id": "MOB-TANIA-009",
    "activo": "ACT-MOV-2026-006",
    "colaborador": "Tania Tarazona",
    "cargo": "Coordinadora de Despacho & Logística",
    "area": "Logística & Despacho",
    "dispositivo": "Xiaomi Redmi Note 15",
    "modeloExacto": "24116RN98G",
    "marca": "Xiaomi",
    "colorEquipo": "Ice Blue",
    "linea": "954 321 098",
    "operador": "Claro PE",
    "imei1": "869102068291039",
    "imei2": "869102068291047",
    "serial": "30192/B9281726",
    "soc": "MediaTek Helio G99-Ultra / G100 (6nm @ 2.2 GHz)",
    "gpu": "ARM Mali-G57 MC2 Dual-Core @ 950 MHz",
    "ramTotalGB": 8,
    "ramTipo": "LPDDR4X",
    "romTotalGB": 256,
    "romTipo": "UFS 2.2 Flash Storage",
    "romUsado": "38.9 GB",
    "romLibre": "217.1 GB",
    "pantalla": "6.67\" AMOLED FHD+ 120Hz (2400x1080 px), 1800 nits",
    "bateria": "5,000 mAh Li-Po",
    "bateriaSalud": "100%",
    "bateriaCarga": "Turbo Charge 33W USB Type-C",
    "camaras": "Triple: 108 MP Principal (1/1.67\") + 8 MP Ultra Gran Angular 118° + 2 MP Macro | Frontal 16 MP",
    "so": "Android 15 • Xiaomi HyperOS v2.0.2",
    "parche": "2026-02-01",
    "red": "Dual SIM 4G VoLTE • Wi-Fi 5 Dual-Band • BT 5.2 • NFC • IR Blaster",
    "seguridad": "Sensor de huellas óptico bajo pantalla • Certificación IP54",
    "observaciones": "Terminal de operaciones de campo para coordinación de transportistas, seguimiento satelital y recepción de mercadería.",
    "pdfReport": "reports/2026-09-07_Informe_Auditoria_Celular_TANIA_TARAZONA.pdf",
    "image": "images/phone_xiaomi_redmi_note13_blue.png",
    "isOnline": true
  }
];
